# Generated by Django 5.1 on 2024-08-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_id_chat",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="телеграм id"
            ),
        ),
    ]
