# Generated by Django 5.1 on 2024-08-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=100, verbose_name="Место")),
                (
                    "time_action",
                    models.TimeField(verbose_name="Время (когда выполнить)"),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Действие"
                    ),
                ),
                (
                    "is_nice",
                    models.BooleanField(
                        choices=[("Приятная", True), ("Полезная", False)],
                        default=False,
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="От 1 до 7 дней",
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Награда"
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveSmallIntegerField(
                        help_text="В минутах", verbose_name="Время на выполнение"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        choices=[("Публичная", True), ("Не публичная", False)],
                        default=False,
                        verbose_name="Признак публичности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
