# Generated by Django 5.1 on 2024-08-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_nice",
            field=models.BooleanField(
                default=False, verbose_name="Признак приятной привычки"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False, verbose_name="Признак публичности"
            ),
        ),
    ]
